@rootURL = http://localhost:5062

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books/
Accept: application/json

###
GET {{rootURL}}/api/books/1
Accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json
{
    "title": "O Enterro do Velho Punk",
    "author": "Thomas Pappon",
    "yearPublished": 2025
}

###
PUT {{rootURL}}/api/books/2
Content-Type: application/json
{
    "id": 2,
    "title": "Sandman",
    "author": "Neil Gaiman",
    "yearPublished": 1995
}

###
DELETE {{rootURL}}/api/books/2

### 
POST {{rootURL}}/api/authentication/register-user
Content-Type: application/json
{
    "UserName": "User1",
    "Email": "user1@gmail.com",
    "Password": "Pw#1234"
}

###
POST {{rootUrl}}/api/authentication/login-user
Content-Type: application/json
{
    "Email": "user1@gmail.com",
    "Password": "Pw#1234" 
}
